query Design {
  design {
    id
    modules {
      ... on ComponentColumnsOneColumn {
        id
        content
      }
    }
    seo {
      ... on ComponentContentSeo {
        title
        description
        image {
          id
          url
        }
      }
    }
  }
}