query Work {
  work {
    id
    title
    casestudies {
      ... on ComponentCasestudiesCaseStudies {
        id
        case_study {
          id
          title
          type
          image {
            url
            alternativeText
            caption
          }
        }
      }
    }
  }
}