query Work {
  work {
    id
    title
    casestudies {
      ... on ComponentCasestudiesCaseStudies {
        id
        case_study {
          id
          url
          title
          type
          banner {
            url
            alternativeText
            caption
            mime
          }
          media {
            ... on ComponentContentMedia {
              id
              image {
                url
                alternativeText
                caption
              }
              qvideo {
                id
                title
                src
                preview {
                  id
                  url
                  mime
                }
              }
            }
          }
        }
      }
    }
    seo {
      ... on ComponentContentSeo {
        title
        description
      }
    }
  }
}