query About {
  about {
    id
    title
    introduction
    image1 {
      ... on ComponentContentMedia {
        id
        image {
          id
          url
          alternativeText
          mime
        }
        qvideo {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
      }
    }
    image2 {
      ... on ComponentContentMedia {
        id
        image {
          id
          url
          alternativeText
          mime
        }
        qvideo {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
      }
    }
    content {
    	... on ComponentColumnsOneColumn {
        id
        content
      }
    	... on ComponentColumnsTwoColumn {
        id
        content
        media {
          url
          alternativeText
          caption
        }
        reverse
      }
    	... on ComponentColumnsVideo {
        id
        qvideo {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
      }
    }
    expertise {
      ... on ComponentContentselectorContentSelector {
        id
        title
        content
        image {
          id
          url
          alternativeText
          caption
        }
        qvideo {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
      }
    }
    seo {
      ... on ComponentContentSeo {
        title
        description
      }
    }
  }
}