query Contact {
  contact {
    id
    title
    introduction
    address
    visit
    telephone
    email
    coordinates
    seo {
      ... on ComponentContentSeo {
        title
        description
      }
    }
  }
}