query Contact {
  contact {
    id
    introduction
    address
    visit
    telephone
    email
    coordinates
    seo {
      ... on ComponentContentSeo {
        title
        description
        image {
          id
          url
        }
      }
    }
  }
}