query Home {
  home {
    id
    subtitle
    images {
      id
      url
      alternativeText
      mime
    }
    introvideo {
      id
      title
      src
      preview {
        id
        url
        mime
      }
    }
    partners {
      ... on ComponentContentselectorContentSelector {
        id
        title
        content
        image {
          id
          url
          alternativeText
          caption
        }
        qvideo {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
      }
    }
    counters {
      ... on ComponentContentCounter {
        id
        number
        unit
        text
      }
    }
    seo {
      ... on ComponentContentSeo {
        title
        description
      }
    }
  }
}