query Home {
  home {
    id
    title
    qvideo {
      id
      title
      src
    }
    introvideo {
      id
      title
      src
      preview {
        id
        url
        mime
      }
    }
    studionews {
      ... on ComponentStudionewsStudionews {
        id
        description
        label
        url
        urlText
        thumbnail {
          id
          url
          alternativeText
        }
      }
    }
    partners {
      ... on ComponentContentselectorContentSelector {
        id
        title
        content
        image {
          id
          url
          alternativeText
          caption
        }
        qvideo {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
      }
    }
    counters {
      ... on ComponentContentCounter {
        id
        number
        unit
        text
      }
    }
    seo {
      ... on ComponentContentSeo {
        title
        description
        image {
          id
          url
        }
      }
    }
  }
}