query Home {
  home {
    id
    title
    introvideo {
      id
      title
      src
      preview {
        id
        url
        mime
      }
    }
    modules {
    	... on ComponentColumnsOneColumn {
        id
        content
        backgroundcolor
      }
    	... on ComponentColumnsTwoColumn {
        id
        content
        media {
          url
          alternativeText
          caption
          mime
        }
        reverse
        backgroundcolor2
      }
    }
    studionews {
      ... on ComponentStudionewsStudionews {
        id
        description
        label
        url
        urlText
        thumbnail {
          id
          url
          alternativeText
        }
      }
    }
    partners {
      ... on ComponentContentselectorContentSelector {
        id
        title
        content
        image {
          id
          url
          alternativeText
          caption
        }
        qvideo {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
      }
    }
    seo {
      ... on ComponentContentSeo {
        title
        description
        image {
          id
          url
        }
      }
    }
  }
}