query Menu {
  menu {
    id
    navigation {
      title
      route
      inverttext
      background {
        id
        url
      }
      backgroundimage {
        id
        url
      }
    }
  }
}