query Articles ($url: String!) {
  articles (where: { url: $url }) {
    id
    url
    title
    content
    image {
      id
      url
      alternativeText
      caption
    }
    category {
      id
      name
      colour
    }
    published_at
    seo {
      ... on ComponentContentSeo {
        title
        description
        image {
          id
          url
        }
      }
    }
  }
}