query ArticlesByCategory ($id: ID!, $start: Int) {
  category (id: $id) {
    name
    articles (limit: 10, start: $start, sort: "published_at:DESC", where: { published: true }) {
      id
      url
      title
      content
      image {
        url
        alternativeText
        caption
      }
      category {
        id
        name
        colour
      }
      published_at
    }
  }
}