query Articles ($url: String!) {
  articles (where: { url: $url }) {
    id
    url
    title
    content
    image {
      url
      alternativeText
      caption
    }
    category {
      name
      colour
    }
    published_at
  }
}