query Articles ($start: Int) {
  articles (limit: 10, start: $start, sort: "published_at:DESC", where: { published: true }) {
    id
    title
    content
    image {
      url
      alternativeText
      caption
    }
    category {
      name
    }
    published_at
  }
}