query CaseStudies ($url: String!) {
  caseStudies (where: { url: $url }) {
    id
    url
    title
    inverttext
    textposition
    banner {
      id
      url
      mime
    }
    mobilebannger {
      id
      url
    }
    thumbnail {
      id
      url
      mime
    }
    thumbnailPosition
    media {
      ... on ComponentContentMedia {
        id
        image {
          id
          url
          alternativeText
          mime
        }
        qvideo {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
      }
    }
    type
    introduction
    content
    client
    whatwedid
    relatedwork {
      id
      url
      title
      thumbnail {
        id
        url
        alternativeText
      }
      type
    }
    case_study {
      id
      title
      inverttext
      banner {
        url
        mime
      }
    }
    modules {
      ... on ComponentModulesVideo {
        id
        content
        image {
          id
          url
          alternativeText
          caption
          mime
        }
        qvideo {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
        fullscreen
        backgroundcolour
      }
      ... on ComponentModules1X1Textleft {
        id
        mainimage {
          id
          url
          alternativeText
          caption
          mime
        }
        mainvideo {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
        image {
          url
          alternativeText
          caption
          mime
        }
        qvideo {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
        content
        contentposition
        backgroundcolour2
      }
      ... on ComponentModules1X1Textright {
        id
        mainimage {
          id
          url
          alternativeText
          caption
          mime
        }
        mainvideo {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
        image {
          id
          url
          alternativeText
          caption
          mime
        }
        qvideo {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
        content
        contentposition2
        backgroundcolour3
      }
      ... on ComponentModules1X1 {
        id
        column1content
        column1image {
          id
          url
          alternativeText
          caption
          mime
        }
        column1video {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
        column2content
        column2image {
          id
          url
          alternativeText
          caption
          mime
        }
        column2video {
          id
          title
          src
          preview {
            id
            url
            mime
          }
        }
        backgroundcolour4
      }
      ... on ComponentModulesQuote {
        id
        quote
        citation
        backgroundcolour5
      }
      ... on ComponentModulesGallery {
        id
        title
        images {
          id
          url
          alternativeText
          caption
        }
        backgroundcolour6
      }
    }
    published
    seo {
      ... on ComponentContentSeo {
        title
        description
      }
    }
  }
}