name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Yarn Install
      run: yarn install
    - name: Prepare generation
      run: echo Preparing deployment with linked server at $SCHEMA_PATH
      env:
        SCHEMA_PATH: http://18.132.131.54:1337/graphql
    - name: Generate the site
      run: yarn generate
      env:
        SCHEMA_PATH: http://18.132.131.54:1337/graphql
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CACHE_CONTROL: "max-age=31536000"
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "dist"
